### ISSUE TITLE
doris基于docker-compose部署，请教调用streamload遇到的问题

### ISSUE THREAD

**Issue by xeon-ye** [TurboWay/DorisClient#3]
调用streamload后，获取be时拿到的是docker网络的地址而不是宿主的地址，只能去做替换。不太确认这是docker-compose编排的问题还是代码需要增加兼容性。    
url = self._get_be(table, headers)
        headers['label'] = self._label(table)
        headers['columns'] = self._columns(dict_array[0].keys())
        **url= url.replace("172.20.80.3","192.168.3.225")**
        response = requests.put(url, json.dumps(dict_array), headers=headers, allow_redirects=False)
        if response.status_code == 200:

**Comment by TurboWay** [comment]
> 调用streamload后，获取be时拿到的是docker网络的地址而不是宿主的地址，只能去做替换。不太确认这是docker-compose编排的问题还是代码需要增加兼容性。 url = self._get_be(table, headers) headers['label'] = self._label(table) headers['columns'] = self._columns(dict_array[0].keys()) **url= url.replace("172.20.80.3","192.168.3.225")** response = requests.put(url, json.dumps(dict_array), headers=headers, allow_redirects=False) if response.status_code == 200:

这个be的地址其实也是doris返回的，所以代码上目前应该是没什么可以调的。
